CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TYPE pci_status AS ENUM ('DRAFT','IN_PROGRESS','VALIDATED','PUBLISHED');
CREATE TYPE record_status AS ENUM ('ACTIVE','ARCHIVED','INACTIVE');
CREATE TYPE rule_severity AS ENUM ('ERROR','WARNING','RECOMMENDATION');
